In [1]:
from learningAgent import ReinforceAlgorithm
from environment import Model, AdversaryModes
import numpy as np

In [2]:
game = Model(totalDemand = 400, 
               tupleCosts = (57, 71),
               totalStages = 25,
               initState = [400/2,0], adversaryMode=AdversaryModes.myopic)

In [7]:
Qtable = np.zeros((20,4))


In [8]:
algorithm = ReinforceAlgorithm(game, Qtable, numberEpisodes=10000, discountFactor =0.9)

In [9]:
algorithm.solver()

208 130 131.5 5694 208
201 126 135.0 5175 205
194 124 138.5 4690 201
207 131 132.0 5624 207
209 131 131.0 5772 209
190 123 140.5 4422 198
204 129 133.5 5400 206
208 132 131.5 5700 207
209 131 131.0 5772 209
190 123 140.5 4422 198
198 126 136.5 4968 203
199 126 136.0 5037 204
200 128 135.5 5112 203
205 129 133.0 5472 207
206 131 132.5 5550 206
199 125 136.0 5032 204
202 129 134.5 5256 204
190 121 140.5 4416 199
201 127 135.0 5180 205
195 123 138.0 4752 202
198 124 136.5 4958 204
207 130 132.0 5621 208
193 124 139.0 4623 200
191 121 140.0 4480 200
198 125 136.5 4964 203
192 124 139.5 4556 199
199 126 136.0 5037 204
208 131 131.5 5698 208
205 131 133.0 5476 206
192 121 139.5 4544 201
191 122 140.0 4485 200
203 130 134.0 5329 205
198 126 136.5 4968 203
208 131 131.5 5698 208
206 130 132.5 5548 207
206 129 132.5 5544 207
203 128 134.0 5325 206
208 130 131.5 5694 208
196 124 137.5 4824 202
209 130 131.0 5767 209
193 122 139.0 4615 201
199 126 136.0 5037 204
206 130 132.5 5548 207
193 122 139

In [10]:
print(Qtable)

[[ 868.11  376.62 1540.51    0.  ]
 [ 426.83  459.26  220.44  333.56]
 [ 860.27  288.81  456.13    0.  ]
 [ 722.44  472.1   580.69  290.37]
 [ 793.01 2575.86  343.71    0.  ]
 [ 746.1   296.41  395.07  417.71]
 [ 874.09  315.27  654.14    0.  ]
 [ 263.71  355.3   232.81  289.57]
 [1235.88  853.87  304.84    0.  ]
 [ 773.6  1225.69  224.39  310.68]
 [ 825.5   580.12  788.57    0.  ]
 [2848.67  578.16  344.77  449.98]
 [ 802.51  247.95  675.5     0.  ]
 [ 408.55  573.63  357.33  676.45]
 [ 785.81 1160.35  625.76    0.  ]
 [ 436.77  962.62  337.15  733.65]
 [1501.13  715.67  766.31    0.  ]
 [ 962.75 1123.46 1728.94  372.48]
 [6170.6  1191.33 1321.35    0.  ]
 [ 653.86 2039.67  875.13  611.73]]
