In [1]:
from learningAgent import ReinforceAlgorithm
from environment import Model, AdversaryModes
import numpy as np

In [2]:
game = Model(totalDemand = 400, 
               tupleCosts = (57, 71),
               totalStages = 25,
               initState = [400/2,0], adversaryMode=AdversaryModes.myopic)

In [3]:
Qtable = np.zeros((20,4))


In [4]:
algorithm = ReinforceAlgorithm(game, Qtable, numberEpisodes=10000, discountFactor =0.9)

In [5]:
algorithm.solver()

In [6]:
print(Qtable)

[[ 725.21  436.81  424.6     0.  ]
 [ 408.61  560.26  340.3   323.39]
 [1295.23  485.24  450.7     0.  ]
 [ 377.53  539.95  231.91  352.36]
 [ 799.4   356.25  890.06    0.  ]
 [ 356.84  458.72  589.29  470.86]
 [1319.92  636.47  404.86    0.  ]
 [ 321.   1479.85 1045.11  402.96]
 [3518.3   466.89  305.57    0.  ]
 [ 430.17  279.07  477.45  586.05]
 [ 927.24  455.24  409.29    0.  ]
 [ 570.79 2188.28  322.77  444.04]
 [1268.24  375.19  428.19    0.  ]
 [ 246.98  461.79  274.08  255.2 ]
 [1657.57  313.    278.23    0.  ]
 [ 785.09  580.14  542.23  267.24]
 [1001.59  572.73  373.02    0.  ]
 [3736.54  917.09  682.92  930.21]
 [2689.15 6064.97  497.11    0.  ]
 [ 422.27  958.8   902.96  721.55]]
