In [1]:
from Environment import env, AdversaryModes
import numpy as np
import torch
from stable_baselines3 import PPO
from stable_baselines3.ppo.policies import MlpPolicy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines3.common.callbacks import EvalCallback
import matplotlib.pyplot as plt
import gymnasium as gym
import numpy as np

In [2]:
adversary_probabilities = torch.zeros(len(AdversaryModes))
adversary_probabilities[0]=1

In [3]:
if __name__ == "__main__":

    num_cpu = 8
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=1)

    model.learn(total_timesteps=1_000_000)

Using cpu device
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 25       |
|    ep_rew_mean     | 1.65e+05 |
| time/              |          |
|    fps             | 8035     |
|    iterations      | 1        |
|    time_elapsed    | 2        |
|    total_timesteps | 16384    |
---------------------------------


In [4]:
# number_of_rounds = 100

In [5]:
# deterministic_payoffs = [0]*number_of_rounds
# random_payoffs = [0]*number_of_rounds
# standard_deviation = [0]*number_of_rounds
# for round in range(number_of_rounds):
#     model.learn(total_timesteps=20_000)
#     deterministic_payoff, _ = evaluate_policy(model, vec_env, n_eval_episodes=10, warn=False, deterministic= True)
#     random_reward, std_reward = evaluate_policy(model, vec_env, n_eval_episodes=100, warn=False, deterministic= False)
#     deterministic_payoffs[round] = deterministic_payoff
#     random_payoffs[round] = random_reward
#     standard_deviation[round] = std_reward

In [6]:
def run_episode(env):                
        episode_memory = list()

        state = env.reset()
        done = [False]

        while not done[0]:
            action, _ = model.predict(state, deterministic=True)
            previous_state = state
            state, reward, done, _ = env.step(action)
            episode_memory.append([previous_state[0], action[0], reward[0]])

        states, actions, rewards = list(zip(*episode_memory))

        return states, actions, rewards

In [7]:
states, actions, rewards = run_episode(vec_env)

In [8]:
states

(array([  0, 200]),
 array([  1, 224]),
 array([  2, 229]),
 array([  3, 220]),
 array([  4, 226]),
 array([  5, 224]),
 array([  6, 224]),
 array([  7, 238]),
 array([  8, 239]),
 array([  9, 232]),
 array([ 10, 224]),
 array([ 11, 223]),
 array([ 12, 229]),
 array([ 13, 227]),
 array([ 14, 234]),
 array([ 15, 244]),
 array([ 16, 235]),
 array([ 17, 242]),
 array([ 18, 237]),
 array([ 19, 229]),
 array([ 20, 232]),
 array([ 21, 238]),
 array([ 22, 238]),
 array([ 23, 244]),
 array([ 24, 236]))