In [1]:
from Environment import env, AdversaryModes
import numpy as np
import torch
from stable_baselines3 import PPO
from stable_baselines3.ppo.policies import MlpPolicy
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.vec_env import DummyVecEnv, SubprocVecEnv
from stable_baselines3.common.callbacks import EvalCallback
import matplotlib.pyplot as plt
import gymnasium as gym
import numpy as np

In [2]:
adversary_probabilities = torch.zeros(len(AdversaryModes))
adversary_probabilities[0]=1

In [3]:
if __name__ == "__main__":

    num_cpu = 1  
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=2)

In [4]:
if __name__ == "__main__":

    num_cpu = 2 
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [5]:
if __name__ == "__main__":

    num_cpu = 3
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [6]:
if __name__ == "__main__":

    num_cpu = 4 
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [7]:
if __name__ == "__main__":

    num_cpu = 5
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [8]:
if __name__ == "__main__":

    num_cpu = 6 
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [9]:
if __name__ == "__main__":

    num_cpu = 7
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [10]:
if __name__ == "__main__":

    num_cpu = 8
    vec_env = make_vec_env(env, n_envs=num_cpu, seed=0, vec_env_cls=SubprocVecEnv,
                           env_kwargs=dict(total_demand = 400, tuple_costs = (57, 71), total_stages = 25, adversary_probabilities = adversary_probabilities))
    model = PPO("MlpPolicy", vec_env, verbose=0)

    model.learn(total_timesteps=200_000)

In [13]:
def run_episode(env):                
        episode_memory = list()

        state = env.reset()
        done = False

        while not done:
            action, _ = model.predict(state, deterministic=True)
            previous_state = state
            state, reward, done, _ = env.step(action)
            episode_memory.append([previous_state, action, reward])

        states, actions, rewards = list(zip(*episode_memory))

        return states, actions, rewards

In [14]:
states, actions, rewards = run_episode(vec_env)

In [17]:
rewards

(array([4788.25]),
 array([3836.0625]),
 array([7405.015625]),
 array([5048.84765625]),
 array([8615.57128906]),
 array([7136.03344727]),
 array([5080.20758057]),
 array([6600.68275452]),
 array([7307.56326675]),
 array([6785.36005497]),
 array([8520.98356843]),
 array([6804.24845558]),
 array([6923.07822718]),
 array([5776.32201651]),
 array([7564.11167783]),
 array([6420.99407546]),
 array([6396.54418079]),
 array([7214.46469472]),
 array([5812.23360246]),
 array([7422.99101542]),
 array([5483.50785994]),
 array([7671.91257554]),
 array([6806.35615934]),
 array([7060.95246902]),
 array([7595.0091001]))