In [1]:
from learningAgents import ReinforceAlgorithm
from environmentModel import Model, AdversaryModes
from NeuralNetwork import NeuralNetwork
import torch
import torch.nn as nn
from torch.distributions import Categorical
import time
import matplotlib.pyplot as plt

In [2]:
torch.manual_seed(0)
adversaryProbs=torch.zeros(len(AdversaryModes))
adversaryProbs[0]=1
game = Model(totalDemand = 400, 
               tupleCosts = (57, 71),
              totalStages = 25, adversaryProbs=adversaryProbs)

In [ ]:
st = time.time()
neuralNet=NeuralNetwork(lr = 0.0001, num_input= 2, num_actions=50, nn_dim = 200)
algorithm = ReinforceAlgorithm(game, neuralNet, numberBatches=201, numberEpiPerBatch=100)
algorithm.solver()
ft = time.time()
print("Time:", ft-st)

tensor([0.0195, 0.0186, 0.0225, 0.0212, 0.0195, 0.0189, 0.0182, 0.0195, 0.0208,
        0.0201, 0.0191, 0.0204, 0.0203, 0.0199, 0.0209, 0.0205, 0.0202, 0.0205,
        0.0186, 0.0180, 0.0201, 0.0205, 0.0191, 0.0201, 0.0221, 0.0196, 0.0198,
        0.0187, 0.0207, 0.0214, 0.0211, 0.0174, 0.0236, 0.0186, 0.0191, 0.0208,
        0.0211, 0.0194, 0.0213, 0.0202, 0.0193, 0.0198, 0.0226, 0.0186, 0.0201,
        0.0194, 0.0207, 0.0215, 0.0184, 0.0177], grad_fn=<SoftmaxBackward0>)
tensor([0.0255, 0.0169, 0.0238, 0.0216, 0.0192, 0.0129, 0.0150, 0.0137, 0.0225,
        0.0232, 0.0230, 0.0166, 0.0208, 0.0221, 0.0211, 0.0197, 0.0147, 0.0105,
        0.0145, 0.0129, 0.0201, 0.0222, 0.0125, 0.0196, 0.0358, 0.0204, 0.0155,
        0.0172, 0.0265, 0.0167, 0.0279, 0.0226, 0.0325, 0.0175, 0.0125, 0.0202,
        0.0223, 0.0207, 0.0346, 0.0149, 0.0187, 0.0176, 0.0200, 0.0149, 0.0205,
        0.0154, 0.0292, 0.0305, 0.0142, 0.0164], grad_fn=<SoftmaxBackward0>)
tensor([0.0283, 0.0148, 0.0242, 0.0195, 0.0174

In [ ]:
import pandas as pd
learning = pd.DataFrame(algorithm.returns,columns=['entry'])

In [ ]:
learning.plot()

In [ ]:
learning.max()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
learning = learning.to_numpy()

In [ ]:
learning_2 = [0]*len(learning)
for i in range(len(learning_2)):
    learning_2[i] = learning[i][0]

In [ ]:
plt.plot(learning_2)
plt.show()

In [ ]:
# avg_learning = np.convolve(learning_2, np.ones(1000)/1000, mode = 'valid')

In [ ]:
# plt.plot(avg_learning)
# plt.show()